url: https://rpmerchandisers.github.io/
baseurl:

# Site settings
title: RP MERCHANDISERS
email: VEERA.RAGAVAN.1996@GMAIL.COM
description: "RP MERCHANDISERS - Rice Mandi"




# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: #
  - title: facebook
    url: #

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
